CREATE PROCEDURE INSERT_ACTIVO(@ID_ACTIVO SMALLINT,  @CONDICION VARCHAR(30), @PLACA INT, @DESCRIPCION VARCHAR(150), @GARANTIA VARCHAR(20))
AS
    INSERT INTO ACTIVOS(ID_ACTIVO, CONDICION) VALUES (
        @ID_ACTIVO,
        @CONDICION
    )
    INSERT INTO TIPOS(ID_ACTIVO, PLACA, DESCRIPCION, GARANTIA) VALUES (
        @ID_ACTIVO,
        @PLACA,
        @DESCRIPCION,
        @GARANTIA
    )
GO
