CREATE PROCEDURE INSERT_ACTIVO(@CONDICION VARCHAR(30),@AREA_NOMBRE CHAR(30),@PLACA INT, @DESCRIPCION VARCHAR(150), @GARANTIA VARCHAR(20), @ID_UBICACION SMALLINT)
AS
    INSERT INTO ACTIVOS(CONDICION,AREA_NOMBRE, ID_UBICACION) VALUES (
        @CONDICION,
        @AREA_NOMBRE,
        @ID_UBICACION
    )
    INSERT INTO TIPOS(PLACA, DESCRIPCION, GARANTIA) VALUES (
        @PLACA,
        @DESCRIPCION,
        @GARANTIA
    );
GO

CREATE PROC DELETE_ACTIVO(@ID_ACTIVO SMALLINT)
AS  
    DELETE FROM ACTIVO
    WHERE @ID_ACTIVO = ID_ACTIVO

    DELETE FROM TIPOS
    WHERE @ID_ACTIVO = ID_ACTIVO;
GO

CREATE PROC UPDATE_ACTIVOS(@ID_ACTIVO SMALLINT,@CONDICION VARCHAR(30),@AREA_NOMBRE CHAR(30),@PLACA INT, @DESCRIPCION VARCHAR(150), @GARANTIA VARCHAR(20))
AS
    UPDATE ACTIVOS
    SET
    [CONDICION] = @CONDICION,
    [AREA_NOMBRE] = @AREA_NOMBRE,
    [PLACA] = @PLACA,
    [DESCRIPCION] = @DESCRIPCION,
    [GARANTIA] = @GARANTIA
    WHERE @ID_ACTIVO = ID_ACTIVO;
GO

