USE INVENTARIO_IACSA
GO

CREATE OR ALTER VIEW ACTIVO_PRESTAMO_VIEW
AS 

    SELECT ACT.NOMBRE_ACTIVO,ACT.ID_ACTIVO, ACT.AREA_NOMBRE, ACT.ID_UBICACION,PRE.ESTADO, PRE.FECHA_DE, PRE.FECHA_SO, PRE.ID_PRESTAMO, PRE.ID_ACTIVO AS ID_ACTIVO_PRESTAMO FROM ACTIVOS AS ACT
    INNER JOIN PRESTAMOS AS PRE 
        ON (ACT.ID_ACTIVO = PRE.ID_ACTIVO)
    WHERE PRE.ESTADO = 1
    
    GO
    
    
GO

SELECT * FROM ACTIVO_PRESTAMO_VIEW
GO
SELECT * FROM PRESTAMOS

