CREATE PROC INSERT_AREA(@NOMBRE CHAR(30),@LOGO VARCHAR(50),@ENCARGADO SMALLINT,@ID_INSTITUCION SMALLINT)
AS 
    INSERT INTO AREA(NOMBRE,LOGO,ENCARGADO,ID_INSTITUCION) VALUES(
        @NOMBRE,@LOGO,@ENCARGADO,@ID_INSTITUCION
    )
GO

CREATE PROC DELETE_AREA(@NOMBRE CHAR(30))
AS
    DELETE FROM AREA
        WHERE @NOMBRE  = NOMBRE
GO

CREATE PROC UPDATE_AREA(@NOMBRE CHAR(30),@LOGO VARCHAR(50),@ENCARGADO SMALLINT,@ID_INSTITUCION SMALLINT)
AS
    UPDATE AREA
    SET
        [LOGO] = @LOGO,
        [ENCARGADO] = @ENCARGADO,
        [ID_INSTITUCION] = @ID_INSTITUCION
        WHERE @NOMBRE = NOMBRE
    
