USE INVENTARIO_IACSA
GO

CREATE PROC INSERT_AREA(@NOMBRE CHAR(30),@LOGO VARCHAR(50),@ENCARGADO CHAR(40),@ID_INSTITUCION CHAR(40))
AS 
    INSERT INTO AREA(NOMBRE,LOGO,ENCARGADO,ID_INSTITUCION) VALUES(
        @NOMBRE,@LOGO,@ENCARGADO,@ID_INSTITUCION
    )
GO

CREATE PROC DELETE_AREA(@ID_AREA SMALLINT)
AS
    DELETE FROM AREA
        WHERE @ID_AREA  = ID_AREA
GO

CREATE PROC UPDATE_AREA(@ID_AREA SMALLINT,@LOGO VARCHAR(50),@ENCARGADO CHAR(40),@ID_INSTITUCION CHAR(40), @NOMBRE CHAR(30))
AS
    UPDATE AREA
    SET
        [LOGO] = @LOGO,
        [ENCARGADO] = @ENCARGADO,
        [ID_INSTITUCION] = @ID_INSTITUCION,
        [NOMBRE] = @NOMBRE
        WHERE @ID_AREA = ID_AREA
    
