--ACTUALIZA EL ESTADO DE LOS PRESTAMOS SI PRESENTAN ALGUNA MOROSIDAD Y ADEMÁS SE CAMBIA LA FECHA DE CONTROL DE CAMBIOS DEL ACTVIO
CREATE PROC CURSOR_PRESTAMOS
AS
    --DECLARE
        --@ESTADO_UPD VARCHAR(30),
        --@FECHA DATE 
    DECLARE CURSOR1 CURSOR FOR SELECT ESTADO_ACTIVO,FECHA_DE,FECHA_CONTROL FROM PRESTAMOS AS P INNER JOIN CONTROL_ACTIVOS AS C_A ON (P.ID_ACTIVO = C_A.ID_ACTIVO)
    OPEN CURSOR1
    FETCH NEXT FROM CURSOR1 
    WHILE @@FETCH_STATUS = 0
    BEGIN 
        IF FECHA_DE < GETDATE()
        BEGIN    
            UPDATE C_A
            SET 
                [ESTADO_ACTIVO] = "PRESENTA MOROSIDAD",
                [FECHA_CONTROL] = GETDATE()
        END
    END
CLOSE CURSOR1 
DEALLOCATE CURSOR1
--EL CURSOR2 LO QUE SE VA A ENCARGAR DE HACER ES VERIFICAR QUE NO HAYAN CORREOS REPETIDOS EN LA
--RELACION DE USUARIO
GO
CREATE PROC CURSOR2_ACTIVOS
AS
    DECLARE CURSOR2 CURSOR FOR SELECT 
    OPEN CURSOR2
    FETCH NEXT FROM CURSOR2
