--ACTUALIZA EL ESTADO DE LOS PRESTAMOS SI PRESENTAN ALGUNA MOROSIDAD Y ADEMÁS SE CAMBIA LA FECHA DE CONTROL DE CAMBIOS DEL ACTVIO
CREATE OR ALTER PROC CURSOR_PRESTAMOS
AS
    DECLARE
        @ID_ACTIVO  SMALLINT,
        @ESTADO_ACTIVO VARCHAR(30),
        @FECHA_DE DATE,
        @FECHA_CONTROL DATE; 
    DECLARE CURSOR1 CURSOR FOR SELECT C1.ID_ACTIVO,C1.ESTADO_ACTIVO,C1.FECHA_DE,C1.FECHA_CONTROL FROM(SELECT C_A.ID_ACTIVO,C_A.ESTADO_ACTIVO,P.FECHA_DE,C_A.FECHA_CONTROL FROM PRESTAMOS AS P 
    INNER JOIN CONTROL_ACTIVOS AS C_A ON (P.ID_ACTIVO = C_A.ID_ACTIVO)) AS C1;
    OPEN CURSOR1
    FETCH NEXT FROM CURSOR1 INTO @ID_ACTIVO,@ESTADO_ACTIVO,@FECHA_DE,@FECHA_CONTROL;
    WHILE @@FETCH_STATUS = 0
    BEGIN 
        IF @FECHA_DE < GETDATE() AND @ESTADO_ACTIVO <> 'PRESENTA MOROSIDAD'
        BEGIN    
            PRINT('SE ENCONTRÓ UNA MOROSIDAD EN EL PRESTAMO');
            UPDATE CONTROL_ACTIVOS
            SET 
                [ESTADO_ACTIVO] = 'PRESENTA MOROSIDAD',
                [FECHA_CONTROL] = GETDATE()
                WHERE ID_ACTIVO = @ID_ACTIVO
        END
        FETCH NEXT FROM CURSOR1 INTO @ID_ACTIVO,@ESTADO_ACTIVO,@FECHA_DE,@FECHA_CONTROL;
    END
CLOSE CURSOR1 
DEALLOCATE CURSOR1


--ELIMINA MENSAJES GENERADOS AUTÓMATICAMENTE QUE LLEVAN MÁS DE UN MES DE LA TABLA MENSAJES
GO
CREATE OR ALTER PROC CURSOR2_MENSAJES
AS
    DECLARE 
        @ID_MENSAJE SMALLINT,
        @ID_REMITENTE SMALLINT,
        @FECHA_PUBLICACION DATE,
        @FECHA DATE;
        SET @FECHA = GETDATE()-30;
    DECLARE CURSOR2 CURSOR FOR SELECT ID_MENSAJE,ID_REMITENTE,FECHA FROM MENSAJES
    OPEN CURSOR2
    FETCH NEXT FROM CURSOR2 INTO @ID_MENSAJE,@ID_REMITENTE,@FECHA_PUBLICACION;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF (@FECHA_PUBLICACION < @FECHA  OR (@FECHA_PUBLICACION IS NULL)) AND (@ID_REMITENTE IS NULL)
        BEGIN
            EXEC DELETE_MENSAJE @ID_MENSAJE
            PRINT('SE HA EJECUTADO EL CURSOR2')
        END
        FETCH NEXT FROM CURSOR2 INTO @ID_MENSAJE,@ID_REMITENTE,@FECHA_PUBLICACION;
    END;
CLOSE CURSOR2
DEALLOCATE CURSOR2

GO