USE INVENTARIO_IACSA
GO

CREATE INDEX INDEX_ACTIVOS
ON ACTIVOS(ID_ACTIVO,NOMBRE_ACTIVO)

GO

CREATE INDEX INDEX_USUARIOS
ON USUARIOS(ID_USUARIO,CORREO)

GO

CREATE INDEX INDEX_INSTITUCIONES
ON INSTITUCIONES(NOMBRE,CORREO)