USE INVENTARIO_IACSA
GO
CREATE PROC INSERT_INSTITUCIONES(@ID_UBICACION SMALLINT,@NOMBRE VARCHAR(50),@CORREO VARCHAR(30))
AS
    INSERT INTO INSTITUCIONES(ID_UBICACION,NOMBRE,CORREO) VALUES(
        @ID_UBICACION,
        @NOMBRE,
        @CORREO
    )

GO

CREATE PROC DELETE_INSTITUCIONES(@ID_UBICACION SMALLINT,@NOMBRE VARCHAR(50),@CORREO VARCHAR(30))
AS
    DELETE FROM INSTITUCIONES
    WHERE @ID_UBICACION = ID_UBICACION

GO

CREATE PROC UPDATE_INSTITUCIONES(@ID_UBICACION SMALLINT,@NOMBRE VARCHAR(50),@CORREO VARCHAR(30))
AS
    UPDATE INSTITUCIONES
    SET
    [NOMBRE] = @NOMBRE,
    [CORREO] = @CORREO
    WHERE @ID_UBICACION = ID_UBICACION

GO