USE INVENTARIO_IACSA
GO
CREATE PROC INSERT_INSTITUCIONES(@ID_INSTITUCION CHAR(40),@NOMBRE VARCHAR(50),@CORREO VARCHAR(30))
AS
    INSERT INTO INSTITUCIONES(ID_INSTITUCION,NOMBRE,CORREO) VALUES(
        @ID_INSTITUCION,
        @NOMBRE,
        @CORREO
    )

GO

CREATE PROC DELETE_INSTITUCIONES(@ID_INSTITUCION CHAR(40),@NOMBRE VARCHAR(50),@CORREO VARCHAR(30))
AS
    DELETE FROM INSTITUCIONES
    WHERE @ID_INSTITUCION = ID_INSTITUCION

GO

CREATE PROC UPDATE_INSTITUCIONES(@ID_INSTITUCION CHAR(40),@NOMBRE VARCHAR(50),@CORREO VARCHAR(30))
AS
    UPDATE INSTITUCIONES
    SET
    [NOMBRE] = @NOMBRE,
    [CORREO] = @CORREO
    WHERE @ID_INSTITUCION = ID_INSTITUCION

GO