CREATE PROC INSERT_MENSAJE(@ID_MENSAJE SMALLINT,@ASUNTO VARCHAR(50),@CONTENIDO VARCHAR(280))
AS 
INSERT INTO MENSAJES(ID_MENSAJE,ASUNTO,CONTENIDO) VALUES(
    @ID_MENSAJE,@ASUNTO,@CONTENIDO
)

GO

CREATE PROC DELETE_MENSAJE(@ID_MENSAJE SMALLINT,@ASUNTO VARCHAR(75),@CONTENIDO VARCHAR(280))
AS
    DELETE FROM MENSAJES
        WHERE @ID_MENSAJE = ID_MENSAJE

GO

CREATE PROC UPDATE_MENSAJE(@ID_MENSAJE SMALLINT,@ASUNTO VARCHAR(75),@CONTENIDO VARCHAR(280))
AS
    UPDATE MENSAJES
    SET 
        [ASUNTO] = @ASUNTO,
        [CONTENIDO] = @CONTENIDO