USE INVENTARIO_IACSA
GO
--ENVÍA UN MENSAJE CUANDO SE REALIZA UN PRESTAMO AL USUARIO CORRESPONDIENTE AL AREA DONDE SE SOLICITÓ EL PRESTAMO
CREATE OR ALTER TRIGGER [dbo].[PRESTAMO_TRIGGER]
ON  SOLICITANTE
AFTER INSERT
AS
BEGIN
    DECLARE @ID_USUARIO CHAR(40)
    SELECT @ID_USUARIO = ID_USUARIO FROM INSERTED
    INSERT INTO MENSAJES(ID_DESTINATARIO,ASUNTO, CONTENIDO)
    VALUES (
        @ID_USUARIO,
        'NUEVA PRESTAMO SOLICITADO',
        'Se ha solicitado un prestamo a un nuevo activo'
    )
    
END