USE INVENTARIO_IACSA
GO
CREATE PROC INSERT_PRESTAMOS(@ID_ACTIVO SMALLINT,@SOLICITANTE CHAR(40))
AS
    INSERT INTO prestamos(ID_ACTIVO)VALUES(
        @ID_ACTIVO)
    --El solicitante va a ser el id del usuario
    INSERT INTO SOLICITANTE(ID_USUARIO) VALUES(@SOLICITANTE)
GO

CREATE PROC DELETE_PRESTAMOS(@ID_PRESTAMO SMALLINT)
AS
    -- Delete rows from table 'TableName'
    DELETE FROM SOLICITANTE
    WHERE 	ID_PRESTAMO = @ID_PRESTAMO

    -- Delete rows from table 'TableName'
    DELETE FROM [dbo].[PRESTAMOS]
    WHERE 	ID_PRESTAMO = @ID_PRESTAMO
 
GO

CREATE PROCEDURE UPDATE_PRESTAMOS(@id_prestamo SMALLINT,@estado BIT,@fecha_so DATE,@fecha_de DATE)
AS
    UPDATE PRESTAMOS
    SET 
        [ESTADO] = @ESTADO,
        [FECHA_SO] = @FECHA_SO,
        [FECHA_DE] = @FECHA_DE
    WHERE ID_PRESTAMO = @ID_PRESTAMO;
GO

