USE INVENTARIO_IACSA
GO
CREATE OR ALTER TRIGGER [dbo].[PRESTAMO_TRIGGER]
ON  SOLICITANTE
AFTER INSERT
AS
BEGIN
    DECLARE @ID_USUARIO SMALLINT
    SELECT @ID_USUARIO = ID_USUARIO FROM INSERTED
    INSERT INTO MENSAJES(ID_DESTINATARIO,ASUNTO, CONTENIDO)
    VALUES (
        @ID_USUARIO,
        'NUEVA PRESTAMO SOLICITADO',
        'Se ha solicitado un prestamo a un nuevo activo'
    )
    
END