CREATE PROC RESET_DATABASE
AS
BEGIN TRANSACTION
DECLARE
    @ERROR BIT;
    SET @ERROR = 'FALSE';
    DBCC CHECKIDENT ('ACTIVOS',RESEED,0)
    DBCC CHECKIDENT ('TIPOS',RESEED,0)
    DBCC CHECKIDENT ('USUARIOS',RESEED,0)
    DBCC CHECKIDENT ('NOMBRE_USUARIOS',RESEED,0)
    DBCC CHECKIDENT ('MENSAJES',RESEED,0)
    DBCC CHECKIDENT ('AREA',RESEED,0)
    DBCC CHECKIDENT ('UBICACIONES',RESEED,0)
    DBCC CHECKIDENT ('CONTROL_ACTIVOS',RESEED,0)
    DBCC CHECKIDENT ('INSTITUCIONES',RESEED,0)
    DBCC CHECKIDENT ('TELEFONOS',RESEED,0)
    DBCC CHECKIDENT ('PRESTAMOS',RESEED,0)
    DBCC CHECKIDENT ('SOLICITANTE',RESEED,0)
    DROP TABLE NOMBRE_USUARIO
    DROP TABLE MENSAJES
    DROP TABLE CONTROL_ACTIVOS
    DROP TABLE TELEFONOS
    DROP TABLE INSTITUCIONES
    DROP TABLE TIPOS
    DROP TABLE AREA
    DROP TABLE SOLICITANTE
    DROP TABLE ACTVIOS
    DROP TABLE PRESTAMOS
    DROP TABLE USUARIOS
    ROLLBACK TRANSACTION