-- Create a new database called 'INVENTARIO_IACSA'
-- Connect to the 'master' database to run this snippet
USE master
GO
-- Create the new database if it does not exist already
IF NOT EXISTS (
	SELECT [name]
		FROM sys.databases
		WHERE [name] = N'INVENTARIO_IACSA'
)
CREATE DATABASE INVENTARIO_IACSA
GO

USE INVENTARIO_IACSA
GO

-- Drop the database 'INVENTARIO_IACSA'
-- Connect to the 'master' database to run this snippet
USE master
GO
-- Uncomment the ALTER DATABASE statement below to set the database to SINGLE_USER mode if the drop database command fails because the database is in use.
-- ALTER DATABASE INVENTARIO_IACSA SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
-- Drop the database if it exists
IF EXISTS (
	SELECT [name]
		FROM sys.databases
		WHERE [name] = N'INVENTARIO_IACSA'
)
DROP DATABASE INVENTARIO_IACSA
GO

 
CREATE TABLE USUARIOS(
	ID_USUARIO		SMALLINT		NOT NULL,
	CORREO			VARCHAR(50)		NOT NULL,
	AREA			VARCHAR(30)		NOT NULL

	CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO)
);

GO

CREATE TABLE NOMBRE_USUARIO(
	ID_USUARIO SMALLINT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO1 VARCHAR(50) NOT NULL,
	APELLIDO2 VARCHAR(50) NOT NULL
	
	CONSTRAINT FK_NOMBREUSUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
	CONSTRAINT PK_NOMBREUSUARIO PRIMARY KEY (ID_USUARIO)
);
GO

CREATE TABLE PRESTAMOS(
	ID_PRESTAMO		SMALLINT		NOT NULL,
	ID_ACTIVO 		SMALLINT		NOT NULL,
	ESTADO			VARCHAR(50)		NOT NULL,
	TIEMPO_PR		DATE			NOT NULL,
	FECHA_SO		DATE			NOT NULL,
	FECHA_DE		DATE			NOT NULL

	CONSTRAINT PK_PRESTAMOS PRIMARY KEY (ID_PRESTAMO)
	CONSTRAINT FK_PRESTAMOSACTIVOS FOREIGN KEY (ID_ACTIVO) REFERENCES ACTIVOS(ID_ACTIVO)
);

GO

CREATE TABLE SOLICITANTE(
	ID_PRESTAMO SMALLINT NOT NULL,
	ID_USUARIO SMALLINT NOT NULL,

	CONSTRAINT FK_SOLICITANTEPRESTAMO FOREIGN KEY (ID_PRESTAMO) REFERENCES PRESTAMOS(ID_PRESTAMO),
	CONSTRAINT FK_SOLICITANTEUSUARIO FOREIGN KEY (ID_USUARIO)   REFERENCES USUARIOS(ID_USUARIO),
	CONSTRAINT PK_SOLICITANTE PRIMARY KEY (ID_PRESTAMO)


)



CREATE TABLE ACTIVOS(
	ID_ACTIVO		SMALLINT		NOT NULL,
	CONDICION		VARCHAR(30)		NULL

	CONSTRAINT PK_ACTIVOS PRIMARY KEY (ID_ACTIVO)
);

GO

CREATE TABLE TIPOS(
	ID_ACTIVO		SMALLINT		NOT NULL,
	PLACA			INT				NOT NULL,
	DESCRIPCION		VARCHAR(150)	NULL,
	GARANTIA		VARCHAR(20)		NULL,

	CONSTRAINT FK_TIPOS FOREIGN KEY (ID_ACTIVO) REFERENCES ACTIVOS(ID_ACTIVO),
	CONSTRAINT PK_TIPOS PRIMARY KEY (ID_ACTIVO)
);

GO

CREATE TABLE AREA(
	LOGO			VARCHAR(50)		NULL,
	NOMBRE			VARCHAR(50)		NOT NULL,

	CONSTRAINT PK_AREA PRIMARY KEY (NOMBRE)
);

GO

CREATE TABLE CONTROL_ACTIVOS(
	ID_ACTIVO		SMALLINT		NOT NULL,	
	ESTADO_ACTIVO	VARCHAR(30)		NOT NULL,
	FECHA_CONTROL	DATE			NOT NULL,
	
	CONSTRAINT FK_CONTROL_ACTIVOS FOREIGN KEY (ID_ACTIVO) REFERENCES ACTIVOS(ID_ACTIVO),
	CONSTRAINT PK_CONTROL_ACTIVOS PRIMARY KEY (ID_ACTIVO)
);

GO

CREATE TABLE INSTITUCIONES(
	ID_INSTITUCION	TINYINT			NOT NULL,
	NOMBRE			VARCHAR(50)		NOT NULL,
	CORREO			VARCHAR(30)		NOT NULL,

	CONSTRAINT PK_INSTITUCIONES PRIMARY KEY (ID_INSTITUCION)
);

GO

CREATE TABLE UBICACIONES(
	ID_UBICACION	TINYINT			NOT NULL,
	DETALLE			VARCHAR(50)		NULL,
	NOMBRE			VARCHAR(50)		NOT NULL

	CONSTRAINT PK_UBICACIONES PRIMARY KEY (ID_UBICACION)
);

GO

CREATE TABLE TELEFONOS(
	ID_INSTITUCION	TINYINT			NOT NULL,
	NUMERO			CHAR(8)			NOT NULL,

	CONSTRAINT FK_TELEFONOS FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCIONES(ID_INSTITUCION),
	CONSTRAINT PK_TELEFONOS PRIMARY KEY (ID_INSTITUCION)
)

GO

CREATE TABLE MENSAJES(
	ID_MENSAJE		INT				NOT NULL,
	ASUNTO			VARCHAR(75)		NOT NULL,
	CONTENIDO		VARCHAR(280)	NOT NULL

	CONSTRAINT PK_MENSAJES PRIMARY KEY (ID_MENSAJE)
);

GO