USE INVENTARIO_IACSA
GO

CREATE PROC INSERT_TELEFONOS(@ID_INSTITUCION CHAR(40),@NUMERO CHAR(10))
AS
    INSERT INTO TELEFONOS(ID_INSTITUCION,NUMERO) VALUES(
        @ID_INSTITUCION,@NUMERO
    )

GO

CREATE PROC DELETE_TELEFONOS(@ID_INSTITUCION CHAR(40),@NUMERO CHAR(8))
AS
    DELETE FROM TELEFONOS
    WHERE @ID_INSTITUCION = ID_INSTITUCION

GO

CREATE PROC UPDATE_TELEFONOS(@ID_INSTITUCION CHAR(40),@NUMERO CHAR(8))
AS
    UPDATE TELEFONOS
    SET 
    [NUMERO] = @NUMERO
    WHERE @ID_INSTITUCION = ID_INSTITUCION AND @NUMERO = NUMERO

GO