USE INVENTARIO_IACSA
GO
CREATE PROC INSERT_UBICACIONES(@DETALLE VARCHAR(50), @NOMBRE VARCHAR(50), @ID_INSTITUCION CHAR(40))
AS
    INSERT INTO UBICACIONES(ID_INSTITUCION,DETALLE, NOMBRE)VALUES(
        @ID_INSTITUCION,@DETALLE,@NOMBRE)

GO

CREATE PROC DELETE_UBICACIONES(@ID_UBICACION SMALLINT)
AS

    DELETE FROM UBICACIONES
    WHERE 	ID_UBICACION = @ID_UBICACION

 
GO

CREATE PROCEDURE UPDATE_UBICACIONES(@ID_UBICACION SMALLINT,@DETALLE VARCHAR(50),@NOMBRE VARCHAR(50))
AS
    UPDATE UBICACIONES
    SET 
        [DETALLE] = @DETALLE,
        [NOMBRE] = @NOMBRE
        
    WHERE ID_UBICACION = @ID_UBICACION;
GO

