USE INVENTARIO_IACSA
GO
CREATE PROCEDURE INSERT_USUARIO(@ID_USUARIO CHAR(40),@ID_INSTITUCION CHAR(40),@CORREO VARCHAR(50),@NOMBRE VARCHAR(50), @APELLIDO1 VARCHAR(50), @APELLIDO2 VARCHAR(50),@CONTRASENA CHAR(20))
AS
    INSERT INTO USUARIOS(ID_USUARIO,CORREO,CONTRASENA,ID_INSTITUCION) VALUES (
        @ID_USUARIO,
        @CORREO, 
        @CONTRASENA,
        @ID_INSTITUCION
    )
    INSERT INTO NOMBRE_USUARIO(ID_USUARIO, NOMBRE, APELLIDO1, APELLIDO2) VALUES (
        @ID_USUARIO,
        @NOMBRE,
        @APELLIDO1,
        @APELLIDO2
    )
GO

CREATE PROCEDURE INSERT_USUARIOINSTITUCION(@ID_USUARIO CHAR(40),@ID_INSTITUCION CHAR(40),@CORREO VARCHAR(50),@NOMBRE VARCHAR(50), @APELLIDO1 VARCHAR(50), @APELLIDO2 VARCHAR(50),@CONTRASENA CHAR(20), @NOMBRE_INSTITUCION VARCHAR(50), @CORREO_INSTITUCION VARCHAR(30))
AS
    INSERT INTO INSTITUCIONES(ID_INSTITUCION, NOMBRE, CORREO) VALUES (
        @ID_INSTITUCION,
        @NOMBRE_INSTITUCION,
        @CORREO_INSTITUCION
    ) 
    INSERT INTO USUARIOS(ID_USUARIO,CORREO,CONTRASENA,ID_INSTITUCION) VALUES (
        @ID_USUARIO,
        @CORREO, 
        @CONTRASENA,
        @ID_INSTITUCION
    )
    INSERT INTO NOMBRE_USUARIO(ID_USUARIO, NOMBRE, APELLIDO1, APELLIDO2) VALUES (
        @ID_USUARIO,
        @NOMBRE,
        @APELLIDO1,
        @APELLIDO2
    )
GO


CREATE PROCEDURE DELETE_USUARIO(@ID_USUARIO CHAR(40) )
AS

    DELETE FROM [dbo].[NOMBRE_USUARIO]
        WHERE ID_USUARIO = @ID_USUARIO
    
    DELETE FROM [dbo].[USUARIOS]
        WHERE ID_USUARIO = @ID_USUARIO
    
GO

CREATE PROCEDURE UPDATE_USUARIO(@ID_USUARIO CHAR(40) ,@CORREO VARCHAR(50), @NOMBRE VARCHAR(50), @APELLIDO1 VARCHAR(50), @APELLIDO2 VARCHAR(50),@CONTRASENA CHAR(20))
AS
    
    UPDATE [dbo].[NOMBRE_USUARIO]
    SET
        [NOMBRE] = @NOMBRE,
        [APELLIDO1] = @APELLIDO1,
        [APELLIDO2] = @APELLIDO2
        
    WHERE ID_USUARIO = @ID_USUARIO
    
    UPDATE [dbo].[USUARIOS]
    SET
        [CORREO] = @CORREO,
        [CONTRASENA] = @CONTRASENA
    
    WHERE ID_USUARIO = @ID_USUARIO
    
GO


