USE INVENTARIO_IACSA
GO
CREATE PROCEDURE INSERT_USUARIO(@CORREO VARCHAR(50),  @NOMBRE VARCHAR(50), @APELLIDO1 VARCHAR(50), @APELLIDO2 VARCHAR(50))
AS
    INSERT INTO USUARIOS(CORREO) VALUES (
        @CORREO 
    )
    INSERT INTO NOMBRE_USUARIO(NOMBRE, APELLIDO1, APELLIDO2) VALUES (
        @NOMBRE,
        @APELLIDO1,
        @APELLIDO2
    )
GO

CREATE PROCEDURE DELETE_USUARIO(@ID_USUARIO SMALLINT )
AS

    DELETE FROM [dbo].[NOMBRE_USUARIO]
        WHERE ID_USUARIO = @ID_USUARIO
    
    DELETE FROM [dbo].[USUARIOS]
        WHERE ID_USUARIO = @ID_USUARIO
    
GO

CREATE PROCEDURE UPDATE_USUARIO(@ID_USUARIO SMALLINT ,@CORREO VARCHAR(50), @NOMBRE VARCHAR(50), @APELLIDO1 VARCHAR(50), @APELLIDO2 VARCHAR(50) )
AS
    
    UPDATE [dbo].[NOMBRE_USUARIO]
    SET
        [NOMBRE] = @NOMBRE,
        [APELLIDO1] = @APELLIDO1,
        [APELLIDO2] = @APELLIDO2
        
    WHERE ID_USUARIO = @ID_USUARIO
    
    UPDATE [dbo].[USUARIOS]
    SET
        [CORREO] = @CORREO
    
    WHERE ID_USUARIO = @ID_USUARIO
    
GO


