CREATE PROCEDURE INSERT_USUARIO(@ID_USUARIO SMALLINT ,@CORREO VARCHAR(50), @AREA VARCHAR(30), @NOMBRE VARCHAR(50), @APELLIDO1 VARCHAR(50), @APELLIDO2 VARCHAR(50))
AS
    INSERT INTO USUARIOS(CORREO, AREA, ID_USUARIO) VALUES (
        @CORREO,
        @AREA,
        @ID_USUARIO
    )
    INSERT INTO NOMBRE_USUARIO(NOMBRE, APELLIDO1, APELLIDO2, ID_USUARIO) VALUES (
        @NOMBRE,
        @APELLIDO1,
        @APELLIDO2,
        @ID_USUARIO
    )
GO

CREATE PROCEDURE DELETE_USUARIO(@ID_USUARIO SMALLINT )
AS

    DELETE FROM [dbo].[NOMBRE_USUARIO]
        WHERE ID_USUARIO = @ID_USUARIO
    
    DELETE FROM [dbo].[USUARIOS]
        WHERE ID_USUARIO = @ID_USUARIO
    
GO

CREATE PROCEDURE UPDATE_USUARIO(@ID_USUARIO SMALLINT ,@CORREO VARCHAR(50), @NOMBRE VARCHAR(50), @APELLIDO1 VARCHAR(50), @APELLIDO2 VARCHAR(50) )
AS
    
    UPDATE [dbo].[NOMBRE_USUARIO]
    SET
        [NOMBRE] = @NOMBRE,
        [APELLIDO1] = @APELLIDO1,
        [APELLIDO2] = @APELLIDO2
        
    WHERE ID_USUARIO = @ID_USUARIO
    
    UPDATE [dbo].[USUARIOS]
    SET
        [CORREO] = @CORREO
    
    WHERE ID_USUARIO = @ID_USUARIO
    
GO




